config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'rooms#index'
  resources :rooms, only: %i[new show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :room, optional: true
  validates :content, presence: true
  
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :messages
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @rooms = Room.all.order(:id)
  end

  def new
    Room.create!
    redirect_to root_path
  end
  
  def show
    @room = Room.find(params[:id])
    @messages = @room.messages
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <p><%= "#{message.user.email}: #{message.content}" %></p>
</div>

app/views/rooms/index.html.erb
<div>
  <p><% current_user.id %></p>
  <ul>
    <% @rooms.each do |room| %>
      <li><%= link_to "Room#{room.id}", room_path(room) %></li>
    <% end %>
  </ul>
  <li><%= link_to 'NEW ROOM' , new_room_path %></li>
</div>

app/views/rooms/show.html.erb
<div id="messages" data-room_id="<%= @room.id %>">
  <%= render @messages %>
</div>

<%= label nil, nil, 'Say something:' %>
<%= text_field nil, nil, 'data-behavior': 'room_speaker' %>